name: Team branches creation
on:
  push:
    branches:
      - 'master'
jobs:
  job1:
    name: Create team branches
    runs-on: ubuntu-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v3
    - name: Create develop branch
      if: ${{ contains(github.event.head_commit.message, 'CREATE_TEAM_BRANCHES') }}
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'develop'
    - name: Create devGustavo branch
      if: ${{ contains(github.event.head_commit.message, 'CREATE_TEAM_BRANCHES') }}
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'devGustavo'
    - name: Create devNicolas branch
      if: ${{ contains(github.event.head_commit.message, 'CREATE_TEAM_BRANCHES') }}
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'devNicolas'
    - name: Create devHassler branch
      if: ${{ contains(github.event.head_commit.message, 'CREATE_TEAM_BRANCHES') }}
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'devHassler'
    - name: Create release branch
      if: ${{ contains(github.event.head_commit.message, 'CREATE_TEAM_BRANCHES') }}
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'release'
