name: Automerge
on:
  push:
    branches:
      - 'dev**'
      - 'hotfix**'

jobs:
  build-and-test:
  runs-on: ubuntu-latest
  name: Build and test
  steps:
    - uses: actions/checkout@v3
    - uses: ng-easy/npm-install@v1
    - run: npm run build
